spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: et5036et!!
  jpa:
    hibernate:
      ddl-auto: create    # 처음 스키마 자동 생성/수정: create / create-drop / update 중 택1
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true